## http://www-rohan.sdsu.edu/~aty/bibliog/latex/LaTeXtoPDF.html
sudo apt-get install texlive 
sudo apt-get install texlive-base 
sudo apt-get install texlive-base-bin 
sudo apt-get install texlive-common 
sudo apt-get install texlive-font-utils 
sudo apt-get install texlive-fonts-extra 
sudo apt-get install texlive-fonts-recommended 
sudo apt-get install texlive-humanities 
sudo apt-get install texlive-lang-cyrillic 
sudo apt-get install texlive-lang-french 
sudo apt-get install texlive-lang-latin 
sudo apt-get install texlive-latex-base 
sudo apt-get install texlive-latex-extra 
sudo apt-get install texlive-latex-recommended 
sudo apt-get install texlive-math-extra 
sudo apt-get install texlive-pictures 
sudo apt-get install texlive-pstricks
sudo apt-get install latex-beamer 
sudo apt-get install texpower 
sudo apt-get install texlive-pictures 
sudo apt-get install imagemagick
sudo apt-get install python-pygments
